import { GoodsIssue } from '../types/goodsIssue'

export const mockGoodsIssues: GoodsIssue[] = [
  {
    id: 'gi_2024_001',
    issue_no: 'GI-2024-001',
    status: 'Picking',
    partner_id: 'partner_acme',
    partner_code: 'ACME',
    partner_name: 'Acme Retailers',
    from_wh_id: 'wh_central',
    from_wh_code: 'CEN',
    from_wh_name: 'Central WH',
    to_wh_id: 'wh_acme_d1',
    to_wh_code: 'ACME-D1',
    to_wh_name: 'Acme - District 1',
    expected_date: '2024-06-18',
    remark: 'Priority customer order - ship complete if possible.',
    lines: [
      {
        id: 'gi_2024_001_line_1',
        issue_id: 'gi_2024_001',
        line_id: '1',
        product_id: 'prod_1001',
        product_code: 'COFFEE-ARABICA-1KG',
        sku: 'SKU-1001',
        product_name: 'Arabica Coffee Beans 1kg',
        uom_id: 'uom_bag',
        uom: 'bag',
        tracking_type: 'Lot',
        planned_qty: 120,
        picked_qty: 115,
        remark: 'Lot 2024-06A prioritised.'
      },
      {
        id: 'gi_2024_001_line_2',
        issue_id: 'gi_2024_001',
        line_id: '2',
        product_id: 'prod_1045',
        product_code: 'TEA-PREMIUM-500G',
        sku: 'SKU-1045',
        product_name: 'Premium Tea Blend 500g',
        uom_id: 'uom_box',
        uom: 'box',
        tracking_type: 'None',
        planned_qty: 80,
        picked_qty: 80
      }
    ],
    attachments: [
      {
        id: 'attach_gi_2024_001_1',
        filename: 'SO-45829.pdf',
        file_size: 248532,
        file_type: 'application/pdf',
        uploaded_at: '2024-06-15T08:45:00Z'
      }
    ],
    created_at: '2024-06-15T08:42:00Z',
    created_by: 'Nguyen Van A',
    updated_at: '2024-06-16T09:10:00Z',
    updated_by: 'Nguyen Van A',
    submitted_at: '2024-06-15T09:00:00Z',
    submitted_by: 'Nguyen Van A',
    submit_note: 'Submitted after verifying quantities.',
    approved_at: '2024-06-15T12:20:00Z',
    approved_by: 'Pham Thi Approver',
    approved_note: 'Approved with partial pick allowed.'
  },
  {
    partner_name: 'Internal Transfer',
    from_wh_id: 'wh_central',
    from_wh_code: 'CEN',
    from_wh_name: 'Central WH',
    to_wh_id: 'wh_d7',
    to_wh_code: 'D7',
    to_wh_name: 'Warehouse District 7',
    expected_date: '2024-06-19',
    remark: 'Auto generated by replenishment planner.',
    lines: [
      {
        id: 'gi_2024_002_line_1',
        issue_id: 'gi_2024_002',
        line_id: '1',
        product_id: 'prod_2090',
        product_code: 'BOTTLE-330ML',
        sku: 'SKU-2090',
        product_name: 'Glass Bottles 330ml',
        uom_id: 'uom_piece',
        uom: 'pcs',
        tracking_type: 'None',
        planned_qty: 500,
        picked_qty: 500
      },
      {
        id: 'gi_2024_002_line_2',
        issue_id: 'gi_2024_002',
        line_id: '2',
        product_id: 'prod_3099',
        product_code: 'CAP-AL-STD',
        sku: 'SKU-3099',
        product_name: 'Bottle Caps - Aluminum',
        uom_id: 'uom_piece',
        uom: 'pcs',
        tracking_type: 'None',
        planned_qty: 500,
        picked_qty: 498,
        remark: 'Two caps damaged during picking.'
      }
    ],
    attachments: [
      {
        id: 'attach_gi_2024_002_1',
        filename: 'transfer-plan.xlsx',
        file_size: 105672,
        file_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        uploaded_at: '2024-06-14T10:15:00Z'
      }
    ],
    created_at: '2024-06-14T10:10:00Z',
    created_by: 'Tran Thi B',
    updated_at: '2024-06-18T08:05:00Z',
    updated_by: 'Tran Thi B',
    submitted_at: '2024-06-14T10:30:00Z',
    submitted_by: 'Tran Thi B',
    submit_note: 'Ready for transfer routing.',
    approved_at: '2024-06-14T11:00:00Z',
    approved_by: 'System Scheduler',
    approved_note: 'Auto approved by planning engine.'
  },
  {

    lines: [
      {
        id: 'gi_2024_003_line_1',
        issue_id: 'gi_2024_003',
        line_id: '1',
    issue_type: 'Manual',
    issue_method: 'Manual',
    ref_no: 'ADJ-775',
    status: 'Completed',
    partner_id: 'partner_quality_disposal',
    partner_code: 'QD-REC',
    partner_name: 'Quality Disposal',
    from_wh_id: 'wh_central',
    from_wh_code: 'CEN',
    from_wh_name: 'Central WH',
    to_wh_id: 'wh_scrap',
    to_wh_code: 'SCRAP',
    to_wh_name: 'Scrap Yard',
    expected_date: '2024-06-12',
    remark: 'Expired goods sent for disposal.',
    lines: [
      {
        id: 'gi_2024_004_line_1',
        issue_id: 'gi_2024_004',
        line_id: '1',
        product_id: 'prod_9001',
        product_code: 'SNACK-EXPIRED',
        sku: 'SKU-9001',
        product_name: 'Expired Snack Packs',
        uom_id: 'uom_case',
        uom: 'case',
        tracking_type: 'None',
        planned_qty: 150,
        picked_qty: 150
      }
    ],
    attachments: [
      {
        id: 'attach_gi_2024_004_1',
        filename: 'disposal-note.jpg',
        file_size: 58231,
        file_type: 'image/jpeg',
        uploaded_at: '2024-06-10T09:07:00Z'
      }
    ],
    created_at: '2024-06-10T09:05:00Z',
    created_by: 'Le Thi D',
    updated_at: '2024-06-12T15:32:00Z',
    updated_by: 'Le Thi D',
    submitted_at: '2024-06-10T09:20:00Z',
    submitted_by: 'Le Thi D',
    approved_at: '2024-06-10T11:00:00Z',
    approved_by: 'Environmental Officer',
    approved_note: 'Confirmed destruction completed.'
  },
  {
    lines: [
      {
        id: 'gi_2024_005_line_1',
        issue_id: 'gi_2024_005',
        line_id: '1',
      }
    ],
    attachments: [
      {
        id: 'attach_gi_2024_005_1',
        filename: 'return-request.pdf',
        file_size: 88432,
        file_type: 'application/pdf',
        uploaded_at: '2024-06-17T07:15:00Z'
      }
    ],
    created_at: '2024-06-17T07:12:00Z',
    created_by: 'Nguyen Thanh E',
    updated_at: '2024-06-18T06:40:00Z',
    updated_by: 'Nguyen Thanh E',
    submitted_at: '2024-06-17T08:00:00Z',
    submitted_by: 'Nguyen Thanh E',
    submit_note: 'Awaiting vendor confirmation.',
    cancelled_at: '2024-06-19T09:30:00Z',
    cancelled_by: 'Nguyen Thanh E',
    cancelled_reason: 'Vendor withdrew return request.'
  }
]
